services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes:
      - .:/usr/src/app:delegated # Added ':delegated' for Mac speed
    ports:
      - "4000:4000"
      - "35729:35729" # Added the LiveReload port
    user: "501:20"
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve -H 0.0.0.0 --force_polling --watch --livereload --config _config.yml,_config_docker.yml
